 export const teamData = {
  netherlands: [
    {
      id: 1,
      name: "Patrick Henzen",
      role: "Founder & CEO",
      email: "patrick@coseco-services.com",
      linkedin: "https://nl.linkedin.com/in/patrickhenzen",
      image: "https://www.coseco-services.com/wp-content/uploads/2020/11/patrick-bijgesneden-scaled.jpg",
      bio: "Leading the strategic vision and growth of Coseco Services.",
    },
    {
      id: 2,
      name: "Cees Geel",
      role: "Co-founder and COO",
      email: "cees.geel@coseco-services.com",
      linkedin: "https://www.linkedin.com/in/ceesgeel/",
      image: "https://www.coseco-services.com/wp-content/uploads/2020/11/cees-bijgesneden-scaled.jpg",
      bio: "Oversees daily operations and ensures service excellence.",
    },
    {
      id: 3,
      name: "Tommy Heydon",
      role: "Technical Support",
      email: "tommy@coseco-services.com",
      image: "https://www.coseco-services.com/wp-content/uploads/2020/11/Tommy-bijgesneden-scaled.jpg",
      bio: "Provides expert technical support and system maintenance.",
    },
    {
      id: 4,
      name: "Janice Almirante",
      role: "Back Office Manager",
      email: "janice@coseco-services.com",
      linkedin: "https://www.linkedin.com/in/janice-almirante-1bb771b5/",
      image: "https://www.coseco-services.com/wp-content/uploads/2021/05/dddfc0d2-026b-423a-9284-b1f8dd1a58a5-1-2.jpeg",
      bio: "Manages administrative operations and office efficiency.",
    },
    {
      id: 5,
      name: "Femke Henzen",
      role: "Marketing and Content",
      email: "femke@coseco-services.com",
      image: "https://www.coseco-services.com/wp-content/uploads/2021/05/22281880_1609724845714509_8752631759845537636_n-2.jpeg",
      bio: "Creates compelling marketing strategies and content.",
    },
    {
      id: 6,
      name: "Lo Henzen",
      role: "Marketing and Content",
      email: "Lo.henzen@coseco-services.com",
      image: "https://www.coseco-services.com/wp-content/uploads/2023/02/9B085AB9-8664-495C-9B44-A3AE83A80E83.jpeg",
      bio: "Specializes in digital marketing and content creation.",
    },
    {
      id: 7,
      name: "Gladwyn Teo",
      role: "CTO",
      email: "gladwyn@coseco-services.com",
      image: "https://www.coseco-services.com/wp-content/uploads/2020/07/gladwyn_profile.jpg",
      bio: "Leads technological innovation and development.",
    },
  ],
  philippines: [
    {
      id: 8,
      name: "Michael John De Castro",
      role: "General Manager Philippines",
      email: "mike@coseco-services.com",
      image: "https://www.coseco-services.com/wp-content/uploads/2021/03/mike-de-castro.png",
      bio: "Oversees operations and growth in the Philippines region.",
    },
    {
      id: 9,
      name: "Jugel P. Lucero",
      role: "Technical Support Representative",
      email: "jugel.lucero@coseco-services.com",
      image: "https://www.coseco-services.com/wp-content/uploads/2023/02/WhatsApp-Image-2023-02-10-at-02.48.52.jpeg",
      bio: "Provides technical support and customer service.",
    },
  ],
  nepal: [
    {
      id: 10,
      name: "Dipendra Shrestha",
      role: "General Manager Coseco/CEO Ncloud",
      email: "dipendra.shrestha@coseco-services.com",
      image: "https://www.coseco-services.com/wp-content/uploads/2023/02/C959B354-8A2D-4B0F-9BF2-26C20C79D898.jpeg",
      bio: "Leads operations in Nepal and oversees Ncloud initiatives.",
    },
    {
      id: 11,
      name: "Mahendra Kibachhen",
      role: "Business Development Officer",
      email: "mahendra@coseco-services.com",
      image: "https://www.coseco-services.com/wp-content/uploads/2023/02/EDF6F390-D7C7-45C2-9F63-B2B85A20E09F.jpeg",
      bio: "Drives business growth and partnership development.",
    },
    {
      id: 12,
      name: "Rohit Shrestha",
      role: "Technical Manager",
      email: "roheet.shrestha@coseco-services.com",
      image: "https://www.coseco-services.com/wp-content/uploads/2023/02/0159A67E-D2FF-451D-9F66-D391309B36E2.jpeg",
      bio: "Manages technical projects and team coordination.",
    },
  ],
};

export const locations = [
  { id: "all", name: "All Teams", count: 12 },
  { id: "netherlands", name: "Netherlands", count: 7 },
  { id: "philippines", name: "Philippines", count: 2 },
  { id: "nepal", name: "Nepal", count: 3 },
];

export const offices = [
  {
    country: "NETHERLANDS",
    city: "Eindhoven",
    address: "Kastanjelaan 400 (Microlab), 5616 LZ, Eindhoven",
    email: "info@coseco-services.com",
    phone: "+31 85 06 07 437",
  },
  {
    country: "CHINA",
    city: "Hong Kong",
    address: "23F Suit 02, Blk 1 New World Tower, 18 Queen's road Central",
    email: "info@coseco-services.com",
    phone: "+65 8356 8373",
  },
  {
    country: "PHILIPPINES",
    city: "Manila",
    address: "7F Finman Building, 131 Tordesillas St., Salcedo Village, Makati City",
    email: "info@coseco-services.com",
    phone: "+63 917 545 9308",
  },
  {
    country: "NEPAL",
    city: "Kathmandu",
    address: "M8X3+HP4, Guna Kamdev Marg, Kathmandu 44600, Nepal",
    email: "info@coseco-services.com",
    phone: "+977 9851007937",
  },
];